apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: actuator
  name: actuator
  namespace: cnj
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: actuator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: actuator
    spec:
      containers:
      - image: gcr.io/bootiful/cnj-actuator:latest
        imagePullPolicy: Always
        name: cnj-actuator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
